model:
  class_name: model.LVSM_obj_decoder_only.Images2LatentScene

  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 9  # 3 RGB + 3 direction + 3 Reference

  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6  # 3 direction + 3 Reference
  transformer:
    d: 768
    d_head: 64
    n_layer: 24
    special_init: true
    depth_init: true
    use_qk_norm: true

training:
  amp_dtype: bf16
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 12
  beta1: 0.9
  beta2: 0.95
  allowed_gradnorm_factor: 5
  checkpoint_dir: ./experiments/checkpoints/LVSM_12_obj_Med
  checkpoint_every: 2000

  dataset_name: data.dataset_objaverse.ObjaverseDataset
  dataset_path: data/objaverse_v1_in_lvis_25v.txt
  root_path: /workspace/ssd1/objaverse_renderings_25v

  dataset_name2: data.dataset_objaverse.ObjaverseDataset
  dataset_path2: data/objaverse_80k_40v.txt
  root_path2: /workspace/ssd1/obj_40v
  total_frames_per_obj2: 40
  
  grad_accum_steps: 1
  grad_checkpoint_every: 1
  grad_clip_norm: 1.0

  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.5

  lr: 0.0004
  train_steps: 40000

  total_frames_per_obj: 25
  num_input_views: 4
  num_target_views: 3
  num_threads: 8
  num_views: 25
  num_workers: 6
  prefetch_factor: 32
  print_every: 20

  square_crop: true
  target_has_input: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  view_selector:
    max_frame_dist: 192
    min_frame_dist: 25
  vis_every: 1000
  wandb_exp_name: LVSM_obj_Med
  wandb_log_every: 50
  
  wandb_project: LVSM_obj
  warmup: 3000
  weight_decay: 0.05

  # val_dataset_name: data.dataset_gso.GSODataset
  val_dataset_name: data.dataset_gso_ours.GSODataset_ours
  validation_out_dir: ./experiments/checkpoints/LVSM_12_obj_Med
  val_dataset_cfgs:
    root_dir: /workspace/ssd1/gso_render_rv
    suffix: render_mvs_25/model/
    split_file: data/gso_subset64.txt
    if_inference: True
    image_size: 256
    patch_size: 8 

    # for model.process_val_data
    training:
      batch_size_per_gpu: 1
      num_views: 14
      num_input_views: 4
      num_target_views: 10
      target_has_input: false


inference:
  render_video: False
  compute_metrics: True